server:
  port: 8084

spring:
    application:
        name: creditmovement-microservice
    data:
        mongodb:
            host: localhost
            port: 27017
            database: CreditMovement1